// Generated by CoffeeScript 1.7.1
(function() {
  var Layer;

  Layer = function(req, res) {
    this.path = req;
    this.handle = res;
    this.match = function(path) {
      if (path.indexOf(this.path) >= 0) {
        return {
          path: this.path
        };
      }
    };
  };

  module.exports = Layer;

}).call(this);
