// Generated by CoffeeScript 1.7.1
(function() {
  var Layer, p2re;

  p2re = require("path-to-regexp");

  Layer = function(req, res) {
    req = req[req.length - 1] === "/" ? req.slice(0, req.length - 1) : req;
    this.path = req;
    this.handle = res;
    this.match = function(path) {
      var i, item, names, params, paths, re, _i, _len;
      names = [];
      params = {};
      re = p2re(this.path, names, {
        end: false
      });
      paths = re.exec(decodeURIComponent(path));
      if (re.test(path)) {
        for (i = _i = 0, _len = names.length; _i < _len; i = ++_i) {
          item = names[i];
          params[item.name] = paths[i + 1];
        }
        return {
          path: paths[0],
          params: params
        };
      }
    };
  };

  module.exports = Layer;

}).call(this);
