// Generated by CoffeeScript 1.7.1
(function() {
  var http, proto;

  http = require('http');

  proto = {};

  proto.isExpress = true;

  proto.__proto__ = http.IncomingMessage.prototype;

  module.exports = proto;

}).call(this);
