// Generated by CoffeeScript 1.7.1
(function() {
  var http, proto;

  http = require('http');

  proto = {};

  proto.isExpress = true;

  proto.__proto__ = http.ServerResponse.prototype;

  proto.redirect = function(statusCode, path) {
    var res;
    res = this;
    if (path == null) {
      path = statusCode;
      statusCode = 302;
    }
    res.writeHead(statusCode, {
      'Location': path,
      'Content-Length': 0
    });
    res.end();
  };

  module.exports = proto;

}).call(this);
