// Generated by CoffeeScript 1.7.1
(function() {
  var makeRoute;

  makeRoute = function(verb, handler) {
    return function(req, res, next) {
      if (verb === req.method.toLowerCase()) {
        return handler(req, res, next);
      } else {
        return next();
      }
    };
  };

  module.exports = makeRoute;

}).call(this);
