// Generated by CoffeeScript 1.7.1
(function() {
  var makeRoute, methods;

  methods = require('methods');

  makeRoute = function(verb, handler) {
    var route;
    route = function(req, res, next) {
      route.handler(req, res, next);
    };
    route.stack = [];
    route.use = function(verb, handler) {
      this.stack.push({
        verb: verb,
        handler: handler
      });
    };
    route.handler = function(req, res, out) {
      var index, next, stack;
      next = function(err) {
        var layer;
        if (err === "route") {
          out();
        }
        if (err) {
          out(err);
        }
        layer = stack[index++];
        if (!layer) {
          res.statusCode = 404;
          res.end();
        }
        if (layer.verb === req.method.toLowerCase() || layer.verb === "all") {
          layer.handler(req, res, next);
        } else {
          next();
        }
      };
      stack = this.stack;
      index = 0;
      next();
    };
    methods.forEach(function(method) {
      route[method] = function(handler) {
        route.use(method, handler);
        return this;
      };
    });
    return route;
  };

  module.exports = makeRoute;

}).call(this);
